server {
    listen 80;
    server_name _;

    # React Frontend Router
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy to Node API (Port 3000 -> container 3000)
    location /api/ {
        proxy_pass http://visionflow_api:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy to Python AI Engine (Port 8000 -> container 8000)
    location /ai/ {
        # Needs to support SSE
        proxy_pass http://visionflow_engine:8000/ai/;
        proxy_http_version 1.1;
        proxy_set_header Connection '';
        proxy_set_header Host $host;
        proxy_cache off;
        proxy_buffering off;
        chunked_transfer_encoding on;
    }
}
